"""
druid.core.session
~~~~~~~~~~~~~~~~~~

Tracks every operation performed during a DRUID session so that
the full workflow is reproducible and auditable.

Each action (load, inspect, clean, train, …) is logged as a
SessionEvent with a timestamp, operation type, parameters, and
an optional AI rationale. The session can be exported as a Python
script or Jupyter notebook for full reproducibility.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


@dataclass
class SessionEvent:
    """A single tracked operation."""

    operation: str  # e.g. "load", "inspect", "impute", "train"
    params: Dict[str, Any] = field(default_factory=dict)
    code: Optional[str] = None  # Reproducible Python code for this step
    ai_rationale: Optional[str] = None  # Why the AI suggested this
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_dict(self) -> Dict[str, Any]:
        """Serialise to plain dict."""
        return {
            "operation": self.operation,
            "params": self.params,
            "code": self.code,
            "ai_rationale": self.ai_rationale,
            "timestamp": self.timestamp,
        }


class Session:
    """
    Records the history of a DRUID workflow.

    Every call to ``log()`` appends a ``SessionEvent`` to the session
    timeline.  The full history can be exported as JSON or as a
    runnable Python script.

    Parameters
    ----------
    session_id : str, optional
        Unique identifier.  Auto-generated if omitted.
    name : str, optional
        Human-friendly session label.

    Examples
    --------
    >>> session = Session(name="fraud-detection")
    >>> session.log("load", params={"source": "data.csv"}, code="df = pd.read_csv('data.csv')")
    >>> session.log("inspect", ai_rationale="Detected 3 datetime columns")
    >>> len(session)
    2
    """

    def __init__(
        self,
        session_id: Optional[str] = None,
        name: Optional[str] = None,
    ) -> None:
        self.session_id = session_id or uuid.uuid4().hex[:12]
        self.name = name or f"druid-{self.session_id[:8]}"
        self.created_at = datetime.now(timezone.utc).isoformat()
        self._events: List[SessionEvent] = []

    # ---- Core API ----

    def log(
        self,
        operation: str,
        params: Optional[Dict[str, Any]] = None,
        code: Optional[str] = None,
        ai_rationale: Optional[str] = None,
    ) -> None:
        """Record an operation."""
        self._events.append(
            SessionEvent(
                operation=operation,
                params=params or {},
                code=code,
                ai_rationale=ai_rationale,
            )
        )

    @property
    def events(self) -> List[SessionEvent]:
        """Return all logged events (read-only copy)."""
        return list(self._events)

    @property
    def last(self) -> Optional[SessionEvent]:
        """Return the most recent event, or None."""
        return self._events[-1] if self._events else None

    def __len__(self) -> int:
        return len(self._events)

    def __repr__(self) -> str:
        return f"Session(id={self.session_id!r}, name={self.name!r}, events={len(self)})"

    # ---- Export ----

    def to_dict(self) -> Dict[str, Any]:
        """Full session as a serialisable dict."""
        return {
            "session_id": self.session_id,
            "name": self.name,
            "created_at": self.created_at,
            "events": [e.to_dict() for e in self._events],
        }

    def save(self, path: str | Path) -> None:
        """Write session history to a JSON file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            json.dump(self.to_dict(), f, indent=2, default=str)

    def to_script(self) -> str:
        """
        Generate a standalone Python script from logged code blocks.

        Returns
        -------
        str
            Runnable Python source reproducing every logged step.
        """
        lines = [
            "# Auto-generated by DRUID",
            f"# Session: {self.name} ({self.session_id})",
            f"# Created: {self.created_at}",
            "",
            "import pandas as pd",
            "import numpy as np",
            "",
        ]
        for i, event in enumerate(self._events, 1):
            lines.append(f"# --- Step {i}: {event.operation} ---")
            if event.ai_rationale:
                lines.append(f"# AI rationale: {event.ai_rationale}")
            if event.code:
                lines.append(event.code)
            lines.append("")
        return "\n".join(lines)
